github.com:
    oauth_token: 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
    user: pdobrev
    git_protocol: https
    users:
        pdobrev:
            oauth_token: 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
